data:
  database:
    driver: "postgres"
    source: "postgres://postgres:*Abcd123456@postgres:5432/gwa?sslmode=disable"
    migrate: true
    max_idle: 10
    max_open: 100
    max_lifetime: 3600s
    debug: false

  redis:
    network: "tcp"
    addr: "redis:6379"
    password: "*Abcd123456"
    db: 0
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
