data:
  database:
    driver: "postgres"
    source: "host=postgres port=5432 user=postgres password=e2e-test-password dbname=gwa sslmode=disable"
    migrate: true
    debug: false
    enable_trace: false
    enable_metrics: false
    max_idle_connections: 10
    max_open_connections: 10
    connection_max_lifetime: 300s

  redis:
    addr: "redis:6379"
    password: "e2e-test-password"
    dial_timeout: 10s
    read_timeout: 0.4s
    write_timeout: 0.6s
