# Configuration for LCM service OpenAPI generation
version: v2

clean: false

managed:
  enabled: true

  disable:
    - module: buf.build/googleapis/googleapis
    - module: 'buf.build/envoyproxy/protoc-gen-validate'
    - module: 'buf.build/kratos/apis'
    - module: 'buf.build/gnostic/gnostic'
    - module: 'buf.build/gogo/protobuf'
    - module: 'buf.build/tx7do/pagination'
    - module: 'buf.build/menta2k-org/redact'
    - module: buf.build/bufbuild/protovalidate

  override:
    - file_option: go_package_prefix
      value: github.com/go-tangra/go-tangra-portal/api/gen/go

inputs:
  - directory: protos
    paths:
      - protos/lcm/service/v1

plugins:
  # generate openapi v3 yaml doc with menu extensions
  - local: protoc-gen-openapi
    out: ../app/lcm/service/cmd/server/assets
    opt:
      - naming=json
      - depth=2
      - default_response=false
      - enum_type=string
      - output_mode=merged
      - fq_schema_naming=false
